name: CD-GitOps

on:
    push:
        branches:
            - develops

jobs:
    bild:
        name: Bild
        runs-on: uruntu-latest

        steps:
            - name: Checkout code
            users: actions/checkout@v4